import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{vue,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        tertiary: "#9a3b00",
        secondary: "#4c4aca",
        primary: "#0050cb",
        "tertiary-container": "#bb5219",
        "on-secondary-container": "#fffbff",
        "on-tertiary-fixed-variant": "#7c2e00",
        "glass-border-light": "rgba(255, 255, 255, 0.6)",
        "surface-container-low": "#f3f3f5",
        "on-primary": "#ffffff",
        "primary-container": "#0066ff",
        "success-indicator": "#22C55E",
        "glass-surface": "rgba(255, 255, 255, 0.15)",
        "on-primary-container": "#f8f7ff",
        "glass-border-dark": "rgba(255, 255, 255, 0.2)",
        "secondary-fixed-dim": "#c2c1ff",
        outline: "#727687",
        "inverse-surface": "#2f3132",
        "secondary-fixed": "#e2dfff",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8ea",
        "secondary-container": "#6564e4",
        error: "#ba1a1a",
        "on-tertiary-container": "#fff6f3",
        "on-tertiary-fixed": "#351000",
        "on-secondary-fixed-variant": "#3531b4",
        "primary-fixed": "#dae1ff",
        "surface-variant": "#e2e2e4",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9fb",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c2c6d8",
        "surface-dim": "#d9dadc",
        "tertiary-fixed-dim": "#ffb595",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "on-primary-fixed-variant": "#003fa4",
        "on-primary-fixed": "#001849",
        "on-secondary-fixed": "#0b006b",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b3c5ff",
        "surface-tint": "#0054d6",
        "surface-container-highest": "#e2e2e4",
        "on-surface": "#1a1c1d",
        surface: "#f9f9fb",
        "inverse-primary": "#b3c5ff",
        "on-surface-variant": "#424656",
        "surface-container": "#edeef0",
        background: "#f9f9fb",
        "inverse-on-surface": "#f0f0f2",
        "on-background": "#1a1c1d",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "padding-card": "32px",
        "margin-page": "40px",
        "safe-area-top": "64px",
        "gutter-grid": "24px",
        unit: "8px",
      },
      fontFamily: {
        caption: ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        caption: [
          "11px",
          {
            lineHeight: "1.2",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
        "headline-md": [
          "22px",
          {
            lineHeight: "1.3",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "body-lg": [
          "17px",
          {
            lineHeight: "1.5",
            letterSpacing: "-0.01em",
            fontWeight: "400",
          },
        ],
        "display-lg": [
          "40px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.04em",
            fontWeight: "600",
          },
        ],
        "body-md": [
          "15px",
          {
            lineHeight: "1.5",
            letterSpacing: "0",
            fontWeight: "400",
          },
        ],
        "headline-lg": [
          "28px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.03em",
            fontWeight: "600",
          },
        ],
        "label-md": [
          "13px",
          {
            lineHeight: "1.2",
            letterSpacing: "0.01em",
            fontWeight: "500",
          },
        ],
      },
    },
  },
  plugins: [],
} satisfies Config;
